query CartValidationInput {
  cart {
    lines {
      id
      quantity
      merchandise {
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
      lineType: attribute(key: "_promo_engine_line_type") { value }
      offerId: attribute(key: "_promo_engine_offer_id") { value }
      rewardId: attribute(key: "_promo_engine_reward_id") { value }
      offerVersion: attribute(key: "_promo_engine_offer_version") { value }
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
      }
      discountAllocations {
        discountedAmount {
          amount
        }
        discountApplication {
          metafield(namespace: "promo_engine", key: "function_config") {
            value
          }
        }
      }
    }
  }
  validationNode: validation {
    metafield(namespace: "promo_engine", key: "validation_config") {
      value
    }
  }
}
