[workspace]
members = [
    "extensions/discount-function",
    "extensions/cart-transform",
    "extensions/cart-validation",
]
resolver = "2"
exclude = [
    "apps/shopify-admin/extensions/discount-function",
    "apps/shopify-admin/extensions/cart-transform",
    "apps/shopify-admin/extensions/cart-validation",
]

[profile.release]
opt-level = "z"
lto = true
strip = "symbols"
codegen-units = 1
panic = "abort"
