query CartValidationInput {
  cart {
    lines {
      id
      quantity
      merchandise {
        ... on ProductVariant {
          id
          product {
            id
            tags
          }
        }
      }
      attributes {
        key
        value
      }
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
      }
    }
  }
  validationNode: shop {
    metafield(namespace: "promo_engine", key: "validation_config") {
      value
    }
  }
}
