api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "Promo Engine Checkout Upsell"
handle = "promo-engine-checkout-upsell"
uid = "a2a7065f-9de6-4500-b367-70fc73175446"

[[extensions.targeting]]
module = "./src/checkout-upsell.tsx"
target = "purchase.checkout.block.render"

[[extensions.targeting]]
module = "./src/checkout-upsell.tsx"
target = "purchase.checkout.actions.render-before"

[extensions.capabilities]
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "offer_id"
type = "single_line_text_field"
name = "Offer ID"
description = "The promo engine offer ID for this checkout upsell"
