query Input {
  presentmentCurrencyRate
  discount {
    discountClasses
    metafield(namespace: "promo_engine", key: "function_config") {
      value
    }
  }
  cart {
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
    }
    lines {
      quantity
      cost {
        subtotalAmount { amount currencyCode }
      }
      lineTypeAttribute: attribute(key: "_promo_engine_line_type") { value }
      cartGiftTierAttribute: attribute(key: "__cart_gift_tier") { value }
      landingSourceAttribute: attribute(key: "__landing_source") {
        value
      }
      quizBundleIdAttribute: attribute(key: "_quiz_bundle_id") {
        value
      }
      quizFreeGiftAttribute: attribute(key: "_quiz_free_gift") {
        value
      }
      quizExpectedPaidCountAttribute: attribute(key: "_quiz_expected_paid_count") {
        value
      }
      sellingPlanAllocation {
        sellingPlan {
          id
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
        }
      }
    }
    deliveryGroups {
      id
      groupType
      cartLines {
        sellingPlanAllocation {
          sellingPlan {
            id
          }
        }
      }
    }
  }
}
