query Input(
  $c1: String! = "_promo_engine_unused"
  $c2: String! = "_promo_engine_unused"
  $c3: String! = "_promo_engine_unused"
  $customerTags: [String!]! = []
) {
  discount {
    discountClasses
    metafield(namespace: "promo_engine", key: "function_config") {
      value
    }
  }
  cart {
    customCart1: attribute(key: $c1) { value }
    customCart2: attribute(key: $c2) { value }
    customCart3: attribute(key: $c3) { value }
    buyerIdentity {
      customer {
        numberOfOrders
        hasTags(tags: $customerTags) {
          tag
          hasTag
        }
        amountSpent {
          amount
        }
      }
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
        subtotalAmount {
          amount
        }
      }
      sellingPlanAllocation {
        sellingPlan {
          id
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            volumeDiscountTiers: metafield(namespace: "custom", key: "volume_discount_tiers") {
              value
            }
          }
        }
      }
      lineType: attribute(key: "_promo_engine_line_type") {
        value
      }
      landingSource: attribute(key: "__landing_source") {
        value
      }
      volumeDiscountBundleItem: attribute(key: "_bundle_item") {
        value
      }
      volumeDiscountNektarGlp1: attribute(key: "_nektar_glp1") {
        value
      }
      promoMetadata: attribute(key: "_promo_engine_metadata") {
        value
      }
    }
    cost {
      subtotalAmount {
        currencyCode
      }
    }
  }
  presentmentCurrencyRate
  localization {
    country {
      isoCode
    }
  }
}
