query Input(
  $l1: String! = "_promo_engine_unused"
  $l2: String! = "_promo_engine_unused"
  $l3: String! = "_promo_engine_unused"
  $l4: String! = "_promo_engine_unused"
  $l5: String! = "_promo_engine_unused"
  $l6: String! = "_promo_engine_unused"
  $c1: String! = "_promo_engine_unused"
  $c2: String! = "_promo_engine_unused"
  $c3: String! = "_promo_engine_unused"
  $customerTags: [String!]! = []
) {
  discount {
    discountClasses
    metafield(namespace: "promo_engine", key: "function_config") {
      value
    }
  }
  cart {
    customCart1: attribute(key: $c1) { value }
    customCart2: attribute(key: $c2) { value }
    customCart3: attribute(key: $c3) { value }
    sourceAttribute: attribute(key: "source") {
      value
    }
    buyerIdentity {
      customer {
        numberOfOrders
        hasTags(tags: $customerTags) {
          tag
          hasTag
        }
        amountSpent {
          amount
        }
      }
    }
    lines {
      customLine1: attribute(key: $l1) { value }
      customLine2: attribute(key: $l2) { value }
      customLine3: attribute(key: $l3) { value }
      customLine4: attribute(key: $l4) { value }
      customLine5: attribute(key: $l5) { value }
      customLine6: attribute(key: $l6) { value }
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
        subtotalAmount {
          amount
        }
      }
      sellingPlanAllocation {
        sellingPlan {
          id
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            volumeDiscountTiers: metafield(namespace: "custom", key: "volume_discount_tiers") {
              value
            }
          }
        }
      }
      lineType: attribute(key: "_promo_engine_line_type") {
        value
      }
      cartGiftTier: attribute(key: "__cart_gift_tier") {
        value
      }
      promoMetadata: attribute(key: "_promo_engine_metadata") {
        value
      }
    }
    cost {
      subtotalAmount {
        currencyCode
      }
    }
  }
  localization {
    country {
      isoCode
    }
  }
}
