// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/apps/promo-engine/customer/order-attribution": {
    params: {};
  };
  "/apps/promo-engine/product-customizations": {
    params: {};
  };
  "/apps/promo-engine/analytics": {
    params: {};
  };
  "/api/cron/analytics-cleanup": {
    params: {};
  };
  "/apps/promo-engine/evaluate": {
    params: {};
  };
  "/api/offers/:id/export": {
    params: {
      "id": string;
    };
  };
  "/api/products/search": {
    params: {};
  };
  "/api/products/search/collections": {
    params: {};
  };
  "/api/offers/export": {
    params: {};
  };
  "/api/products/sync": {
    params: {};
  };
  "/api/report-error": {
    params: {};
  };
  "/api/cron/offers": {
    params: {};
  };
  "/api/markets": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/webhooks/*": {
    params: {
      "*": string;
    };
  };
  "/api/sync": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/integrations": {
    params: {};
  };
  "/app/diagnostics": {
    params: {};
  };
  "/app/translation": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/analytics/offer/:id": {
    params: {
      "id": string;
    };
  };
  "/app/customize": {
    params: {};
  };
  "/app/migration": {
    params: {};
  };
  "/app/boosters": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/settings/installation": {
    params: {};
  };
  "/app/settings/inventory": {
    params: {};
  };
  "/app/settings/pos": {
    params: {};
  };
  "/app/offers": {
    params: {};
  };
  "/app/offers/import": {
    params: {};
  };
  "/app/offers/:id": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/multicurrency": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/combination": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/conditions": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/priority": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/schedule": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/preview": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/rewards": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/widget": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/widget/market": {
    params: {
      "id": string;
    };
  };
  "/app/offers/:id/debug": {
    params: {
      "id": string;
    };
  };
  "/app/offers/new": {
    params: {};
  };
  "/app/offers/new/discount/:template": {
    params: {
      "template": string;
    };
  };
  "/app/offers/new/bundle/:template": {
    params: {
      "template": string;
    };
  };
  "/app/offers/new/upsell/:template": {
    params: {
      "template": string;
    };
  };
  "/app/offers/new/gift/:template": {
    params: {
      "template": string;
    };
  };
  "/app/logs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/apps/promo-engine/customer/order-attribution" | "/apps/promo-engine/product-customizations" | "/apps/promo-engine/analytics" | "/api/cron/analytics-cleanup" | "/apps/promo-engine/evaluate" | "/api/offers/:id/export" | "/api/products/search" | "/api/products/search/collections" | "/api/offers/export" | "/api/products/sync" | "/api/report-error" | "/api/cron/offers" | "/api/markets" | "/api/health" | "/auth/login" | "/webhooks/*" | "/api/sync" | "/auth/*" | "/app" | "/app/integrations" | "/app/diagnostics" | "/app/translation" | "/app/analytics" | "/app/analytics/offer/:id" | "/app/customize" | "/app/migration" | "/app/boosters" | "/app/settings" | "/app/settings/installation" | "/app/settings/inventory" | "/app/settings/pos" | "/app/offers" | "/app/offers/import" | "/app/offers/:id" | "/app/offers/:id/multicurrency" | "/app/offers/:id/combination" | "/app/offers/:id/conditions" | "/app/offers/:id/priority" | "/app/offers/:id/schedule" | "/app/offers/:id/preview" | "/app/offers/:id/rewards" | "/app/offers/:id/widget" | "/app/offers/:id/widget/market" | "/app/offers/:id/debug" | "/app/offers/new" | "/app/offers/new/discount/:template" | "/app/offers/new/bundle/:template" | "/app/offers/new/upsell/:template" | "/app/offers/new/gift/:template" | "/app/logs";
  };
  "routes/apps.promo-engine.customer.order-attribution.ts": {
    id: "routes/apps.promo-engine.customer.order-attribution";
    page: "/apps/promo-engine/customer/order-attribution";
  };
  "routes/apps.promo-engine.product-customizations.ts": {
    id: "routes/apps.promo-engine.product-customizations";
    page: "/apps/promo-engine/product-customizations";
  };
  "routes/apps.promo-engine.analytics.ts": {
    id: "routes/apps.promo-engine.analytics";
    page: "/apps/promo-engine/analytics";
  };
  "routes/api.cron.analytics-cleanup.ts": {
    id: "routes/api.cron.analytics-cleanup";
    page: "/api/cron/analytics-cleanup";
  };
  "routes/apps.promo-engine.evaluate.ts": {
    id: "routes/apps.promo-engine.evaluate";
    page: "/apps/promo-engine/evaluate";
  };
  "routes/api.offers.$id.export.ts": {
    id: "routes/api.offers.$id.export";
    page: "/api/offers/:id/export";
  };
  "routes/api.products.search.ts": {
    id: "routes/api.products.search";
    page: "/api/products/search" | "/api/products/search/collections";
  };
  "routes/api.products.search.collections.ts": {
    id: "routes/api.products.search.collections";
    page: "/api/products/search/collections";
  };
  "routes/api.offers.export.ts": {
    id: "routes/api.offers.export";
    page: "/api/offers/export";
  };
  "routes/api.products.sync.ts": {
    id: "routes/api.products.sync";
    page: "/api/products/sync";
  };
  "routes/api.report-error.ts": {
    id: "routes/api.report-error";
    page: "/api/report-error";
  };
  "routes/api.cron.offers.ts": {
    id: "routes/api.cron.offers";
    page: "/api/cron/offers";
  };
  "routes/api.markets.ts": {
    id: "routes/api.markets";
    page: "/api/markets";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/webhooks.$.tsx": {
    id: "routes/webhooks.$";
    page: "/webhooks/*";
  };
  "routes/api.sync.ts": {
    id: "routes/api.sync";
    page: "/api/sync";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/integrations" | "/app/diagnostics" | "/app/translation" | "/app/analytics" | "/app/analytics/offer/:id" | "/app/customize" | "/app/migration" | "/app/boosters" | "/app/settings" | "/app/settings/installation" | "/app/settings/inventory" | "/app/settings/pos" | "/app/offers" | "/app/offers/import" | "/app/offers/:id" | "/app/offers/:id/multicurrency" | "/app/offers/:id/combination" | "/app/offers/:id/conditions" | "/app/offers/:id/priority" | "/app/offers/:id/schedule" | "/app/offers/:id/preview" | "/app/offers/:id/rewards" | "/app/offers/:id/widget" | "/app/offers/:id/widget/market" | "/app/offers/:id/debug" | "/app/offers/new" | "/app/offers/new/discount/:template" | "/app/offers/new/bundle/:template" | "/app/offers/new/upsell/:template" | "/app/offers/new/gift/:template" | "/app/logs";
  };
  "routes/app.integrations.tsx": {
    id: "routes/app.integrations";
    page: "/app/integrations";
  };
  "routes/app.diagnostics.tsx": {
    id: "routes/app.diagnostics";
    page: "/app/diagnostics";
  };
  "routes/app.translation.tsx": {
    id: "routes/app.translation";
    page: "/app/translation";
  };
  "routes/app.analytics.tsx": {
    id: "routes/app.analytics";
    page: "/app/analytics" | "/app/analytics/offer/:id";
  };
  "routes/app.analytics.offer.$id.tsx": {
    id: "routes/app.analytics.offer.$id";
    page: "/app/analytics/offer/:id";
  };
  "routes/app.analytics._index.tsx": {
    id: "routes/app.analytics._index";
    page: "/app/analytics";
  };
  "routes/app.customize.tsx": {
    id: "routes/app.customize";
    page: "/app/customize";
  };
  "routes/app.migration.tsx": {
    id: "routes/app.migration";
    page: "/app/migration";
  };
  "routes/app.boosters.tsx": {
    id: "routes/app.boosters";
    page: "/app/boosters";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings" | "/app/settings/installation" | "/app/settings/inventory" | "/app/settings/pos";
  };
  "routes/app.settings.installation.tsx": {
    id: "routes/app.settings.installation";
    page: "/app/settings/installation";
  };
  "routes/app.settings.inventory.tsx": {
    id: "routes/app.settings.inventory";
    page: "/app/settings/inventory";
  };
  "routes/app.settings._index.tsx": {
    id: "routes/app.settings._index";
    page: "/app/settings";
  };
  "routes/app.settings.pos.tsx": {
    id: "routes/app.settings.pos";
    page: "/app/settings/pos";
  };
  "routes/app.offers.tsx": {
    id: "routes/app.offers";
    page: "/app/offers" | "/app/offers/import" | "/app/offers/:id" | "/app/offers/:id/multicurrency" | "/app/offers/:id/combination" | "/app/offers/:id/conditions" | "/app/offers/:id/priority" | "/app/offers/:id/schedule" | "/app/offers/:id/preview" | "/app/offers/:id/rewards" | "/app/offers/:id/widget" | "/app/offers/:id/widget/market" | "/app/offers/:id/debug" | "/app/offers/new" | "/app/offers/new/discount/:template" | "/app/offers/new/bundle/:template" | "/app/offers/new/upsell/:template" | "/app/offers/new/gift/:template";
  };
  "routes/app.offers.import.tsx": {
    id: "routes/app.offers.import";
    page: "/app/offers/import";
  };
  "routes/app.offers._index.tsx": {
    id: "routes/app.offers._index";
    page: "/app/offers";
  };
  "routes/app.offers.$id.tsx": {
    id: "routes/app.offers.$id";
    page: "/app/offers/:id" | "/app/offers/:id/multicurrency" | "/app/offers/:id/combination" | "/app/offers/:id/conditions" | "/app/offers/:id/priority" | "/app/offers/:id/schedule" | "/app/offers/:id/preview" | "/app/offers/:id/rewards" | "/app/offers/:id/widget" | "/app/offers/:id/widget/market" | "/app/offers/:id/debug";
  };
  "routes/app.offers.$id.multicurrency.tsx": {
    id: "routes/app.offers.$id.multicurrency";
    page: "/app/offers/:id/multicurrency";
  };
  "routes/app.offers.$id.combination.tsx": {
    id: "routes/app.offers.$id.combination";
    page: "/app/offers/:id/combination";
  };
  "routes/app.offers.$id.conditions.tsx": {
    id: "routes/app.offers.$id.conditions";
    page: "/app/offers/:id/conditions";
  };
  "routes/app.offers.$id.priority.tsx": {
    id: "routes/app.offers.$id.priority";
    page: "/app/offers/:id/priority";
  };
  "routes/app.offers.$id.schedule.tsx": {
    id: "routes/app.offers.$id.schedule";
    page: "/app/offers/:id/schedule";
  };
  "routes/app.offers.$id.preview.tsx": {
    id: "routes/app.offers.$id.preview";
    page: "/app/offers/:id/preview";
  };
  "routes/app.offers.$id.rewards.tsx": {
    id: "routes/app.offers.$id.rewards";
    page: "/app/offers/:id/rewards";
  };
  "routes/app.offers.$id.widget.tsx": {
    id: "routes/app.offers.$id.widget";
    page: "/app/offers/:id/widget" | "/app/offers/:id/widget/market";
  };
  "routes/app.offers.$id.widget.market.tsx": {
    id: "routes/app.offers.$id.widget.market";
    page: "/app/offers/:id/widget/market";
  };
  "routes/app.offers.$id._index.tsx": {
    id: "routes/app.offers.$id._index";
    page: "/app/offers/:id";
  };
  "routes/app.offers.$id.debug.tsx": {
    id: "routes/app.offers.$id.debug";
    page: "/app/offers/:id/debug";
  };
  "routes/app.offers.new.tsx": {
    id: "routes/app.offers.new";
    page: "/app/offers/new" | "/app/offers/new/discount/:template" | "/app/offers/new/bundle/:template" | "/app/offers/new/upsell/:template" | "/app/offers/new/gift/:template";
  };
  "routes/app.offers.new.discount.$template.tsx": {
    id: "routes/app.offers.new.discount.$template";
    page: "/app/offers/new/discount/:template";
  };
  "routes/app.offers.new.bundle.$template.tsx": {
    id: "routes/app.offers.new.bundle.$template";
    page: "/app/offers/new/bundle/:template";
  };
  "routes/app.offers.new.upsell.$template.tsx": {
    id: "routes/app.offers.new.upsell.$template";
    page: "/app/offers/new/upsell/:template";
  };
  "routes/app.offers.new.gift.$template.tsx": {
    id: "routes/app.offers.new.gift.$template";
    page: "/app/offers/new/gift/:template";
  };
  "routes/app.offers.new._index.tsx": {
    id: "routes/app.offers.new._index";
    page: "/app/offers/new";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.logs.tsx": {
    id: "routes/app.logs";
    page: "/app/logs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/apps.promo-engine.customer.order-attribution": typeof import("./app/routes/apps.promo-engine.customer.order-attribution.ts");
  "routes/apps.promo-engine.product-customizations": typeof import("./app/routes/apps.promo-engine.product-customizations.ts");
  "routes/apps.promo-engine.analytics": typeof import("./app/routes/apps.promo-engine.analytics.ts");
  "routes/api.cron.analytics-cleanup": typeof import("./app/routes/api.cron.analytics-cleanup.ts");
  "routes/apps.promo-engine.evaluate": typeof import("./app/routes/apps.promo-engine.evaluate.ts");
  "routes/api.offers.$id.export": typeof import("./app/routes/api.offers.$id.export.ts");
  "routes/api.products.search": typeof import("./app/routes/api.products.search.ts");
  "routes/api.products.search.collections": typeof import("./app/routes/api.products.search.collections.ts");
  "routes/api.offers.export": typeof import("./app/routes/api.offers.export.ts");
  "routes/api.products.sync": typeof import("./app/routes/api.products.sync.ts");
  "routes/api.report-error": typeof import("./app/routes/api.report-error.ts");
  "routes/api.cron.offers": typeof import("./app/routes/api.cron.offers.ts");
  "routes/api.markets": typeof import("./app/routes/api.markets.ts");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/webhooks.$": typeof import("./app/routes/webhooks.$.tsx");
  "routes/api.sync": typeof import("./app/routes/api.sync.ts");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.integrations": typeof import("./app/routes/app.integrations.tsx");
  "routes/app.diagnostics": typeof import("./app/routes/app.diagnostics.tsx");
  "routes/app.translation": typeof import("./app/routes/app.translation.tsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.tsx");
  "routes/app.analytics.offer.$id": typeof import("./app/routes/app.analytics.offer.$id.tsx");
  "routes/app.analytics._index": typeof import("./app/routes/app.analytics._index.tsx");
  "routes/app.customize": typeof import("./app/routes/app.customize.tsx");
  "routes/app.migration": typeof import("./app/routes/app.migration.tsx");
  "routes/app.boosters": typeof import("./app/routes/app.boosters.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.settings.installation": typeof import("./app/routes/app.settings.installation.tsx");
  "routes/app.settings.inventory": typeof import("./app/routes/app.settings.inventory.tsx");
  "routes/app.settings._index": typeof import("./app/routes/app.settings._index.tsx");
  "routes/app.settings.pos": typeof import("./app/routes/app.settings.pos.tsx");
  "routes/app.offers": typeof import("./app/routes/app.offers.tsx");
  "routes/app.offers.import": typeof import("./app/routes/app.offers.import.tsx");
  "routes/app.offers._index": typeof import("./app/routes/app.offers._index.tsx");
  "routes/app.offers.$id": typeof import("./app/routes/app.offers.$id.tsx");
  "routes/app.offers.$id.multicurrency": typeof import("./app/routes/app.offers.$id.multicurrency.tsx");
  "routes/app.offers.$id.combination": typeof import("./app/routes/app.offers.$id.combination.tsx");
  "routes/app.offers.$id.conditions": typeof import("./app/routes/app.offers.$id.conditions.tsx");
  "routes/app.offers.$id.priority": typeof import("./app/routes/app.offers.$id.priority.tsx");
  "routes/app.offers.$id.schedule": typeof import("./app/routes/app.offers.$id.schedule.tsx");
  "routes/app.offers.$id.preview": typeof import("./app/routes/app.offers.$id.preview.tsx");
  "routes/app.offers.$id.rewards": typeof import("./app/routes/app.offers.$id.rewards.tsx");
  "routes/app.offers.$id.widget": typeof import("./app/routes/app.offers.$id.widget.tsx");
  "routes/app.offers.$id.widget.market": typeof import("./app/routes/app.offers.$id.widget.market.tsx");
  "routes/app.offers.$id._index": typeof import("./app/routes/app.offers.$id._index.tsx");
  "routes/app.offers.$id.debug": typeof import("./app/routes/app.offers.$id.debug.tsx");
  "routes/app.offers.new": typeof import("./app/routes/app.offers.new.tsx");
  "routes/app.offers.new.discount.$template": typeof import("./app/routes/app.offers.new.discount.$template.tsx");
  "routes/app.offers.new.bundle.$template": typeof import("./app/routes/app.offers.new.bundle.$template.tsx");
  "routes/app.offers.new.upsell.$template": typeof import("./app/routes/app.offers.new.upsell.$template.tsx");
  "routes/app.offers.new.gift.$template": typeof import("./app/routes/app.offers.new.gift.$template.tsx");
  "routes/app.offers.new._index": typeof import("./app/routes/app.offers.new._index.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.logs": typeof import("./app/routes/app.logs.tsx");
};