api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "Promo Engine Customer Account"
handle = "promo-engine-customer-account"
uid = "a73241f6-8fbd-4557-9086-db00c190cbc4"

[[extensions.targeting]]
module = "./src/order-attribution.tsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
network_access = true
