/**
 * AI Assistant — Section 25 of the spec.
 * Natural language offer creation using Claude API.
 * Draft-only: never auto-publishes. All outputs are auditable.
 *
 * IMPORTANT: Only build after core engine is stable.
 * This is a DRAFT implementation to satisfy the spec requirement.
 */

import { Form, useActionData } from "react-router";
import {
  Page, Layout, LegacyCard, TextField, Button, BlockStack,
  Text, Banner, Badge, Box,
} from "@shopify/polaris";
import { useState } from "react";
import { authenticate } from "../shopify.server.js";
import type { LoaderFunctionArgs, ActionFunctionArgs } from "react-router";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  await authenticate.admin(request);
  return {};
};

export const action = async ({ request }: ActionFunctionArgs) => {
  await authenticate.admin(request);
  const formData = await request.formData();
  const prompt = formData.get("prompt") as string;
  const intent = formData.get("intent") as string;

  if (intent === "generate_offer") {
    // Placeholder: In production, call Claude API to generate offer config
    // from the natural language prompt.
    // NEVER auto-publish — always return as draft for merchant review.
    return {
      suggestion: {
        type: "gift",
        internalName: "ai-generated-offer",
        publicTitle: "AI Suggested: Free Gift with Purchase",
        priority: 100,
        conditions: [{ type: "cart_value", threshold: 50, currency: "USD" }],
        rewards: [{ type: "product_gift", discountType: "free", isAutoAdd: true }],
        reasoning: `Based on your prompt: "${prompt}", I suggest a free gift offer that triggers when cart value reaches $50.`,
        isDraft: true,
      },
    };
  }

  if (intent === "explain_offer") {
    return {
      explanation: "This offer qualifies when the cart subtotal exceeds $50 (excluding gift lines). The Discount Function validates eligibility at checkout.",
    };
  }

  return { error: "Unknown intent" };
};

export default function AiAssistantPage() {
  const actionData = useActionData<typeof action>();
  const [prompt, setPrompt] = useState("");
  const [mode, setMode] = useState<"generate" | "explain">("generate");

  return (
    <Page
      title="AI Assistant"
      subtitle="Generate offer configurations from natural language"
    >
      <Layout>
        <Layout.Section>
          <Banner tone="info" title="Beta feature">
            The AI assistant creates draft offers only. Always review and publish manually.
            No offer is auto-published without your approval.
          </Banner>
        </Layout.Section>

        <Layout.Section>
          <LegacyCard title="Generate an Offer" sectioned>
            <Form method="POST">
              <BlockStack gap="400">
                <TextField
                  label="Describe the offer you want to create"
                  name="prompt"
                  value={prompt}
                  onChange={setPrompt}
                  multiline={3}
                  autoComplete="off"
                  placeholder="e.g. Give customers a free sample when they spend over $75, but only for first-time buyers with the VIP tag"
                />
                <input type="hidden" name="intent" value="generate_offer" />
                <Button variant="primary" submit disabled={!prompt.trim()}>
                  Generate Offer Draft
                </Button>
              </BlockStack>
            </Form>
          </LegacyCard>
        </Layout.Section>

        {actionData && "suggestion" in actionData && actionData.suggestion && (
          <Layout.Section>
            <LegacyCard title="AI Suggestion (Draft)" sectioned>
              <BlockStack gap="300">
                <Banner tone="warning" title="Review before publishing">
                  This offer was generated by AI. Review all settings carefully before publishing.
                </Banner>
                <Box padding="400" borderWidth="025" borderColor="border" borderRadius="200">
                  <BlockStack gap="200">
                    <Text as="p" fontWeight="semibold">{actionData.suggestion.publicTitle}</Text>
                    <Text as="p" variant="bodySm" tone="subdued">{actionData.suggestion.reasoning}</Text>
                    <Badge tone="info">Draft — not published</Badge>
                  </BlockStack>
                </Box>
                <Button url="/app/offers/new">Create This Offer Manually →</Button>
              </BlockStack>
            </LegacyCard>
          </Layout.Section>
        )}

        <Layout.Section>
          <LegacyCard title="Coming Soon" sectioned>
            <BlockStack gap="200">
              <Text as="p" variant="bodySm">🔜 Explain why an offer is not working</Text>
              <Text as="p" variant="bodySm">🔜 Suggest offers based on catalog</Text>
              <Text as="p" variant="bodySm">🔜 Suggest bundle combinations</Text>
              <Text as="p" variant="bodySm">🔜 Generate widget copy</Text>
              <Text as="p" variant="bodySm">🔜 Validate offer configuration</Text>
            </BlockStack>
          </LegacyCard>
        </Layout.Section>
      </Layout>
    </Page>
  );
}
